### ISSUE TITLE
nextcloud + keeweb

### ISSUE THREAD

**Issue by edzoe** [jhass/nextcloud-keeweb#86] opened 2018-10-24 06:53 UTC
Hello,

I'm running NC 14.0,3 with keeweb 1.5.0 :-)

If I work with the admin account from NC, all is good, the keeweb works well and recognizes the .kdbx. If I switch to a different account, cant open anymore the keepass databases. Any idea where is the problem?

Thank you in advance.

**Comment by jhass** [comment] 2018-10-24 07:19
Duplicate of #40, #83

**Closed by jhass** 2018-10-24 07:19 UTC
