### ISSUE TITLE
Not open kdbx files since nextcloud 12

### ISSUE THREAD

**Issue by CordlessWool** [jhass/nextcloud-keeweb#56] opened 2017-07-13 13:08 UTC
I had the app activate for some time, but decide to deactivate it later... to activate it now again, before I used it with nextcloud 11.0.2 and before. Now I am using nextcloud 12 and activate the app again, but if I click on my kdbx file it only offers me to download it.

Is the keeweb app directly included in the nextcloud app? Because it is not the newest version and missing four bug fix releases.

**Comment by jhass** [comment] 2017-07-13 13:54
No, it's not bundled. 

Duplicate of #34

**Closed** 2017-07-13 13:55 UTC

**Comment by CordlessWool** [comment] 2017-07-14 09:25
From where is KeeWeb linked?

**Comment by jhass** [comment] 2017-07-14 09:39
Sorry I somehow misread your statement, it is indeed bundled. 

I'm currently hesitant to release an update since there were no upstream fixes relevant to the integration or security.
