### ISSUE TITLE
Compatibility with Nextcloud 20

### ISSUE THREAD

**Issue by junpet** [jhass/nextcloud-keeweb#163] opened 2020-10-06 17:23 UTC
Current version is not compatibly with Nextcloud 20. Please add compatibility. Thanks!

**Comment by arnowelzel** [comment] 2020-10-06 19:56
Is Nextcloud 20 already released? On https://apps.nextcloud.com/apps/keeweb I don't see that yet.

**Comment by junpet** [comment] 2020-10-07 09:50
@arnowelzel Yes, it is and you're looking on the wrong page. What you linked tells that this app is not compatible with version 20, but up to 19. What you're searching is this: https://nextcloud.com/changelog/

**Comment by arnowelzel** [comment] 2020-10-07 10:00
Ok, in the past, the non supported version where also listed but with a note, that the app is not supported yet. I also did not get NC 20 yet on my servers.

Well - we have to check first what has changed in NC 20 which might require updating the app.

**Comment by maurerle** [comment] 2020-10-07 22:11
I set up NC20 in a local docker-environment.
I did not find any new issues.
Sync works, sharing with other users works, opening file works.
No errors in console.
I think we can update the max-version to 20

**Comment by arnowelzel** [comment] 2020-10-09 12:16
I try to to some testing as well this weekend and hopefully we can release it soon for NC 20 as well.

**Comment by maurerle** [comment] 2020-10-18 13:09
Could we release it soon?
I just checked if the new unified search in NC20 brings any issues, but it works fine too.
Strg+F in the iframe focuses on the keeweb search bar and otherwise the nextcloud unified search bar is focused.
But it is of course not integrated.

**Comment by Derkades** [comment] 2020-10-28 10:34
Works fine for me as well

**Comment by Art4** [comment] 2020-11-17 21:46
Any updates for NC20 support? Is there something we can do for speeding this up?

**Comment by jhass** [comment] 2020-11-27 08:17
Ref #170

**Comment by arnowelzel** [comment] 2020-11-29 23:26
I just updated the code to provide compatibility with NC20 and fix the build script (d8b1cbdb48968504a3a85ebcb8bc8f64c83747ec) and fixed a compliance warning in the app info (6e19e01ef8566590e9d4783d46b0e319f99f7938). In my test environment (fresh install of NC 20.0.2) I could not find any errors, so I would release it for NC20.

**Comment by jhass** [comment] 2020-11-30 08:35
Should we take the opportunity and include the just released Keeweb 16 too?

**Comment by Brakelmann** [comment] 2020-12-11 13:41
I updated nextcloud to version 20.0.3 and the keeweb app stopped working.
Keeweb used to work fine on version 20.0.2
Can anyone double check, if keeweb still works on 20.0.3.
Thanks, Stefan.

**Comment by Derkades** [comment] 2020-12-11 13:57
@Brakelmann I am getting `Content Security Policy: The page’s settings blocked the loading of a resource at https://domain/apps/keeweb/ (“frame-ancestors”).` in Firefox. It looks like a webserver configuration issue but I don't think I got it before.

**Comment by arnowelzel** [comment] 2020-12-11 14:47
I can confirm that it does not work any longer with 20.0.3. It's another CSP problem. And no - the suggestions in #161 don't work :-(

**Comment by arnowelzel** [comment] 2020-12-11 14:49
CSP - Content Security Policy. Because Keeweb and Nextcloud are very strict about what is allowed and what not, Keeweb does not work any longer and to be honest I don't see any chance to change this soon.

Keeweb was originally designed to be used as a standalone app and not embedded inside websites.

**Comment by arnowelzel** [comment] 2020-12-11 14:52
As a workaround you can just tell Firefox to open it in a new tab, then it works.

**Comment by diserens** [comment] 2020-12-11 22:51
Hello,

the following patch seems to fix it, at least on Chrome and Firefox (doesn't fix the blank page issue on Safari).

`--- keeweb/controller/pagecontroller.php.orig	2020-12-11 23:45:29.086632977 +0100
+++ keeweb/controller/pagecontroller.php	2020-12-11 23:45:16.287059664 +0100
@@ -124,6 +124,7 @@
 		$csp->addAllowedFrameDomain("'unsafe-inline'");
 		$csp->addAllowedFrameDomain("'unsafe-eval'");
 		$csp->addAllowedFrameDomain("blob:");
+		$csp->addAllowedFrameAncestorDomain("'self'");
 		$csp->addAllowedStyleDomain("'self'");
 		$csp->addAllowedFontDomain("'self'");
 		$csp->addAllowedFontDomain("data:");`

**Comment by diserens** [comment] 2020-12-11 22:53
Hi,
the following patch seems to fix it. At least on Chrome and Firefox (doesn't fix the blank page issue on Safari).

--- keeweb/controller/pagecontroller.php.orig	2020-12-11 23:45:29.086632977 +0100
+++ keeweb/controller/pagecontroller.php	2020-12-11 23:45:16.287059664 +0100
@@ -124,6 +124,7 @@
 		$csp->addAllowedFrameDomain("'unsafe-inline'");
 		$csp->addAllowedFrameDomain("'unsafe-eval'");
 		$csp->addAllowedFrameDomain("blob:");
\+		$csp->addAllowedFrameAncestorDomain("'self'");
 		$csp->addAllowedStyleDomain("'self'");
 		$csp->addAllowedFontDomain("'self'");
 		$csp->addAllowedFontDomain("data:");

**Comment by Brakelmann** [comment] 2020-12-12 18:47
> @Brakelmann I am getting `Content Security Policy: The page’s settings blocked the loading of a resource at https://domain/apps/keeweb/ (“frame-ancestors”).` in Firefox. It looks like a webserver configuration issue but I don't think I got it before.
> 
> What's the reason it stopped working for you?

I am getting an internal server error 500 while opening the .kdbx file using chrome.
Did not try Firefox yet. Before upgrading to 20.0.3 my keewb 0.6.3 was running fine.
After the upgrade neither version 0.6.3 nor 0.6.4 is running anymore.
I even tried the patch from diserens without success.

**Comment by arnowelzel** [comment] 2020-12-13 00:37
> 
> 
> Hi,
> the following patch seems to fix it. At least on Chrome and Firefox (doesn't fix the blank page issue on Safari).
> 
> --- keeweb/controller/pagecontroller.php.orig 2020-12-11 23:45:29.086632977 +0100
> +++ keeweb/controller/pagecontroller.php 2020-12-11 23:45:16.287059664 +0100
> @@ -124,6 +124,7 @@
> $csp->addAllowedFrameDomain("'unsafe-inline'");
> $csp->addAllowedFrameDomain("'unsafe-eval'");
> $csp->addAllowedFrameDomain("blob:");
> + $csp->addAllowedFrameAncestorDomain("'self'");
> $csp->addAllowedStyleDomain("'self'");
> $csp->addAllowedFontDomain("'self'");
> $csp->addAllowedFontDomain("data:");

I can confirm that this patch works in NC 20.0.3 with Firefox 83.0 and Vivaldi 3.5.2115.81 (Chromium based) and Edge  87.0.664.60 (Chromium based).

The problems with Safari should be fixed with the proposed removal of the CSP in Keeweb itself.

I'll have to check if this works with Keeweb 16 as well and hopefully we get an updated version within the next days.

**Comment by arnowelzel** [comment] 2020-12-13 00:40
> I am getting an internal server error 500 while opening the .kdbx file using chrome.
> Did not try Firefox yet. Before upgrading to 20.0.3 my keewb 0.6.3 was running fine.
> After the upgrade neither version 0.6.3 nor 0.6.4 is running anymore.
> I even tried the patch from diserens without success.
> UPDATE:
> I gave it try using Firefox, no succes same error message.

@Brakelmann The server logs would be interesting - error 500 usually means there is a PHP error on the server.

**Comment by Brakelmann** [comment] 2020-12-13 14:51
> @Brakelmann The server logs would be interesting - error 500 usually means there is a PHP error on the server.

**@arnowelzel,** I gave it another try today using V0.6.3 keeweb for nextcloud from the app store and patched it manually.
It is working again, I might have done something wrong with checking out latest version from git.

So for me V0.6.3 with the applied patches is working. Thanks, everyone.

**Comment by arnowelzel** [comment] 2020-12-13 19:06
I just created a new version based on Keeweb 1.16.3 and with all proposed patches applied (added CSP for Nextcloud, removed CSP in Keeweb itself).

I tested this version in Nextcloud 20.0.3 - works fine s far:

![grafik](https://user-images.githubusercontent.com/6613614/102021202-6c796200-3d7e-11eb-9845-c542f42d0a60.png)

If you want to test it: https://nextcloud.0x0c.de/s/Tit29WBmdRMFYzF

@jhass If you want to relase this version - I already increased the version number, so it is ready to release. Maybe we should also add tags for releases.

**Comment by jhass** [comment] 2020-12-13 19:51
Should be released :) 

@arnowelzel Thanks for the preparation! There's a github actions workflow now which you can trigger from https://github.com/jhass/nextcloud-keeweb/actions?query=workflow%3ARelease to make a release :)

**Closed by jhass** 2020-12-13 19:51 UTC
Labels: enhancement

**Comment by arnowelzel** [comment] 2020-12-13 20:35
@jhass Is there a mistake? https://apps.nextcloud.com/apps/keeweb lists still version 0.6.4 but I changed the version to 0.6.5 with b258fc8427063d6b5c77690a6cd5790c1d588c52 

JFTR: my ZIP file with the beta version still had 0.6.4, I commited the change afterwards

**Comment by arnowelzel** [comment] 2020-12-13 20:46
Everything is OK, i forgot that the last official release was 0.6.3 and not 0.6.5 ;-)
