### ISSUE TITLE
Keeweb makes nextcloud slower

### ISSUE THREAD

**Issue by Smaig** [jhass/nextcloud-keeweb#24] opened 2016-11-16 12:58 UTC
Hello team,

Each time I enable the Keeweb apps, browsing into nextcloud becomes slower.

### Steps to reproduce
1. Enable file keeweb app
2. Browse into your directories (file app)
3. Feeling that it slower than before enabling Keeweb

### Expected behaviour
No such difference between before and after enabling the app Keeweb

### Actual behaviour

Really slower than before enabling the app Keeweb
### Server configuration

**Operating system**: Linux 4.4.0-1029-raspi2 #36-Ubuntu SMP armv7l armv7l armv7l GNU/Linux

**Web server:** nginx 1.11.5 with ngx_cache_purge module 2.3 and geoip

**Database:** mariadb 10.0.27

**PHP version:** php 7.0.13

**Nextcloud version:** nextcloud 10.0.1

**Where did you install Nextcloud from:** /var/www/nextcloud/

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - announcementcenter: 2.0.0
  - audioplayer: 1.2.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - documents: 0.13.1
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_clipboard: 0.5.0
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - keeweb
  - news: 9.0.4
  - notifications: 0.3.0
  - ownbackup: 0.3.8
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - spreedme: 0.3.3
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - external
  - files_retention
  - firstrunwizard
  - gallery
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocil10fg9af5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.com",
            "192.168.1.20"
        ],
        "datadirectory": "\/var\/nc_data",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/mydomain.com\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "logtimezone": "Europe\/Paris",
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "log_rotate_size": 1048576,
        "quota_include_external_storage": false,
        "knowledgebaseenabled": false,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "filesystem_check_changes": 1,
        "installed": true,
        "appstore.experimental.enabled": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nuage",
        "mail_domain": "mydomain.com",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.server.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie"
        ]
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration

**Browser:** Chrome 54.0.2840.99 m

**Operating system:** Windows 7
#### Nextcloud log (/var/nc_data/owncloud.log)

```
No error logs
```
#### Browser log with Keeweb

```
GET /core/search/templates/part.results.html
GET https://mydomain.com/ocs/v2.php/apps/notifications/api/v1/notifications?format=json
GET /index.php/apps/documents/ajax/mimes.php
GET /apps/encryption/ajax/getStatus
PROPFIND https://mydomain.com/remote.php/webdav/
GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F 200 2543ms	
GET https://mydomain.com/ocs/v1.php/apps/files_external/api/v1/mounts?format=json 200 4333ms	
GET /index.php/apps/files_external/userglobalstorages/1?testOnly=false 200 1935ms	
GET /index.php/apps/files_external/userglobalstorages/2?testOnly=false 200 3931ms	
GET /index.php/apps/files_external/userglobalstorages/3?testOnly=false 200 8057ms	
GET /index.php/apps/files_external/userglobalstorages/5?testOnly=false 200 5778ms	
GET https://mydomain.com/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 200 2307ms	
GET https://mydomain.com/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 200 2023ms	
```
#### Browser log without Keeweb

```
GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F 200 317ms	
GET https://mydomain.com/ocs/v1.php/apps/files_external/api/v1/mounts?format=json 200 700ms	
GET /apps/encryption/ajax/getStatus
PROPFIND https://mydomain.com/remote.php/webdav/
GET /index.php/apps/files_external/userglobalstorages/1?testOnly=false 200 1163ms	
GET /index.php/apps/files_external/userglobalstorages/2?testOnly=false 200 389ms	
GET /index.php/apps/files_external/userglobalstorages/3?testOnly=false 200 751ms	
GET /index.php/apps/files_external/userglobalstorages/5?testOnly=false 200 1421ms
GET https://mydomain.com/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 200 521ms	
```

As you can see, delay are much longer with than whitout Keeweb.
I didn't find any other logs to provide to show this delay...

**Comment by muppeth** [comment] 2016-11-17 01:01
I can confirm. It brought my nextcloud to a crawl. Took me good few bours to realise what is causing it. I havent found anything in the logs.

**Comment by jhass** [comment] 2016-11-24 18:49
This is probably strongly related to #1, if not a duplicate of it.

**Comment by zerojay** [comment] 2016-11-30 17:00
I'm on FreeBSD and I'm not running into this issue.

**Comment by tarator** [comment] 2017-11-09 08:29
Same here. Installed it from the Nextcloud backend. Even after uninstalling the Keeweb app. Nextcloud stays terribly slow. How can I fix this problem?

**Comment by tarator** [comment] 2017-11-09 08:30
@muppeth can you remember how you fixed it?

**Comment by muppeth** [comment] 2017-11-09 11:45
@tarator it's been a while. I dont think I ever managed to fix it. In my comment I referred to the fact I found out that keeweb was responsible for poor performance of nextcloud.
I no longer use it as I moved to pass.
Sorry.

**Comment by jhass** [comment] 2019-02-11 20:05
I still think this was a duplicate of #1

**Closed by jhass** 2019-02-11 20:05 UTC
Labels: enhancement, help wanted
