### ISSUE TITLE
Keeweb client database location setup

### ISSUE THREAD

**Issue by Biopticon** [jhass/nextcloud-keeweb#41] opened 2017-01-27 21:12 UTC
Since I am a novice in Linux, my questions could be naive. 

I created a Keepass database by using Keepass v 2.35 on my PC. I can access that by using a password and a key file. I then exported its database to my NextCloud (v 10.0.1 Keeweb app successfully. I can now access it from any browser by going to my NextCloud account. All works fine. Thank you. But here are my questions:

1) When I click on the arrow to login to Keeweb app on NC using a browser on my PC, it requires, as well as my password, entering a key file from my local drive not from the location in the NextCloud server (although the key file is in the same directory as the keeweb database in NC).  So I enter the key file from from my local drive on my PC and enter Keeweb successfully.  How do I access this key file from the server instead of from my local drive? Is it possible to enter Keeweb just by using just a password without a key file? Or, is it possible to load the key file from the location on the NC server automatically so that I do not have to select it each time I need to enter Keeweb? 

2) I would like to use a kind of Keeweb client on my iPhone and access its database stored on my NC mentioned above. I downloaded an app called MiniKeepass to my iPhone. But this app has no way of defining a location for the database access. So, could you please recommend an app to run on iPhone in which I can define the keepass database stored in NC and some guidance to define this location in the app? Currently I use a commercial Password management program which stores its database in a cloud!

**Comment by agentdr8** [comment] 2017-01-27 22:09
For 1), see [#7](https://github.com/jhass/nextcloud-keeweb/issues/7). Upstream keeweb needs to support keyfiles via webdav.

For 2) you'll want an iOS client that can open kdbx files via webdav. I'm not aware of any, but I'm also not an iOS user. If you were on Android, I'd highly recommend Keepass2Android which has webdav capabilities.

**Comment by Biopticon** [comment] 2017-01-30 02:40
Ok. Thank you. I am not sure how to implement opening the key file through webDav though. I will wait until this feature is part of the application. 
I need a client app that runs under iOS and that its database can be hosted by NC. It seems I have to wait for that one too.

**Comment by ccghad** [comment] 2017-01-30 09:31
Hi @Biopticon you can use KyPass for iOS devices to access Keepass files via Webdav 
[https://itunes.apple.com/de/app/kypass-3/id536560380?mt=8](url)

**Comment by jhass** [comment] 2017-01-30 10:04
Question answered and as noted partly a duplicate of #7, closing.

**Closed by jhass** 2017-01-30 10:04 UTC
