### ISSUE TITLE
Save Configuration

### ISSUE THREAD

**Issue by OMNiTRiX98** [jhass/nextcloud-keeweb#140] opened 2020-03-17 16:22 UTC
KeeWeb v1.12.3 (9b07bbd, 2020-02-14)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

When I open a kdbx File on my Nextcloud in KeeWeb and edit the settings, the configuration is lost as soon as I log off from the Nextcloud. Is there any way to save the settings or set the kdbx File as default for my account?

**Comment by maurerle** [comment] 2020-05-13 13:55
Saving configurations is not implemented yet and it doesn't seem that there will is capacity left for this currently. 
This issue is a duplicate of #106

In your case it would be best to mark your database as favourite in Nextcloud and access it from there by clicking on it.

**Closed** 2020-05-13 13:59 UTC
