### ISSUE TITLE
Cannot see "New" function

### ISSUE THREAD

**Issue by joe-average-user** [jhass/nextcloud-keeweb#117] opened 2019-11-18 09:59 UTC
Looking at your demo I recognised that in my installation of 0.5.1 I cannot see the "new" function. I was already wondering how one would create a new kdbx file with the app. I use it on nextcloud 14.0.14. "open" and "more" are there though...

**Comment by jhass** [comment] 2019-11-18 10:01
Duplicate of #102

**Closed by jhass** 2019-11-18 10:01 UTC

**Comment by joe-average-user** [comment] 2019-11-18 11:28
I am sorry, but I do not request a new function for keeweb. The only thing I say is that looking at _your_ demo image I can see "open" "new" and "more".
Looking at my installation I can only see "open" and "more". There is no "new". I don't start with clicking on a file like your demo does, but I click onto the app in the top bar.

**Comment by jhass** [comment] 2019-11-18 13:03
Ah yes, the video is from a very early version. I disabled that as Keeweb added an option to do so because of the above issues.  Because having a new button there would is actually quite misleading in my opinion. You can always get the desktop app or use app.keeweb.info, which doesn't claim  any integration into a  service, to create new files.
