### ISSUE TITLE
Nextcloud 23

### ISSUE THREAD

**Issue by MiRei777** [jhass/nextcloud-keeweb#195] opened 2021-12-15 11:59 UTC
In NC23 the errorlog generate permanaent massive warnings:

"app":"keeweb","method":"POST","url":"/settings/apps/disable","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36","version":"23.0.0.10","id":"61b9d873cd6c7"}

**Comment by Potemkinkuliss** [comment] 2022-01-29 09:14
It is the same for me:
"app":"keeweb","method":"GET","url":"/ocs/v2.php/search/providers/settings_apps/search?term=mail&from=%2Fsettings%2Fadmin%2Flogging","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0","version":"23.0.0.10"}

**Comment by arnowelzel** [comment] 2022-02-26 14:37
It seems this is a warning message which is only logged when debug messages are enabled in the log. The application still works fine though - Nextcloud just warns about using a deprecated implementation.

The reason is, that this was the implementation needed for older Nextcloud version - and Keeweb started long before Nextcloud 20.

I'll work migrating the code newer Application class structure as it is recommended for Nextcloud 20 or newer, but this may take some time. Until then you may just disable the debug messages to get rid of those warnings.

**Comment by Webxorcist** [comment] 2022-03-28 13:04
As of Nextcloud 23.0.3 this add on seems to be completely broken. Once it is loaded, every Nextcloud page shows "Bad Gateway" until I disable it using the occ tool.

**Comment by arnowelzel** [comment] 2022-03-28 13:07
Sorry to hear that - but for me it works fine even with NC 23.0.3. Can you provide server logs for this?

**Comment by Webxorcist** [comment] 2022-03-28 14:21
I have the loglevel on 0, according to the documentation this is the highest possible level, but all I am getting in the log is this:

`{"reqId":"iEUr61Bh1J4M1uykep9w","level":0,"time":"2022-03-28T13:40:01+00:00","remoteAddr":"","user":"--","app":"keeweb","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"23.0.3.2"}`

But I think I found something, and if that is true you can ignore my post. It seems I had a rights problem in the appdata cache for the /appinfo/app.php. Somehow this triggers way more when keeweb is loaded. I fixed this and now I can't reproduce.

Maybe this is also a cache issue, it seems Keeweb is ignoring the dark mode theme.

Thanks for your fast reply.

**Comment by arnowelzel** [comment] 2022-05-17 12:27
Please do not use log level 0 for production systems! This means to log **everything** including debug and info messages.

For regular use you should only use level 2 to get warnings, errors and fatal errors.

In `config/config.php` of your Nextcloud installation make sure that the loglevel is set to 2:

```
  'loglevel' => 2,
```

Also see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html.

**Comment by arnowelzel** [comment] 2024-01-04 18:06
Closing this issue since it is not relevant any longer. NC 24 is not supported any more.

**Closed by arnowelzel** 2024-01-04 18:06 UTC
Labels: bug, needs investigation
