### ISSUE TITLE
Not opening in IOS Safari

### ISSUE THREAD

**Issue by nassim-2000** [jhass/nextcloud-keeweb#168] opened 2020-11-04 22:53 UTC
When I click to open my database while on safari, I have a completely black screen.

**Comment by maurerle** [comment] 2020-11-05 13:39
this looks like a (dark mode?) duplicate of #161

safari does not allow the unsafe content security policy. The app therefore does not work on safari

**Comment by Delurkdotcom** [comment] 2020-11-05 14:18
Same issue, keeweb won't works on Safari white/blank screen.
iOS 14.1
Nextcloud 19

**Comment by nassim-2000** [comment] 2020-11-05 15:17
> this looks like a (dark mode?) duplicate of #161
> 
> safari does not allow the unsafe content security policy. The app therefore does not work on safari


It was working fine for a while. Also, when I go to this page : https://app.keeweb.info , everything is displayed correctly.

**Comment by esmail** [comment] 2020-12-03 19:35
This is definitely a duplicate of #161; workaround here:
https://github.com/jhass/nextcloud-keeweb/issues/161#issuecomment-737135588

**Closed** 2020-12-03 19:44 UTC
