### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by johnnydvc** [jhass/nextcloud-keeweb#23] opened 2016-11-13 22:49 UTC
Hey,
I've installed the plugin on my nextcloud server but I'm having the following error when opening a kdbx file.
thank you

`Exception: {"Exception":"Exception","Message":"template file not found: template:keeweb","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(197): OC\\Template\\TemplateFileLocator->find('keeweb')\n#1 \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(84): OC_Template->findTemplate('', 'keeweb', 'keeweb')\n#2 \/var\/www\/owncloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(151): OC_Template->__construct('keeweb', 'keeweb', '')\n#3 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#4 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Keeweb\\Controller\\PageController), 'keeweb')\n#5 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('PageController', 'keeweb', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/var\/www\/owncloud\/lib\/base.php(983): OC\\Route\\Router->match('\/apps\/keeweb\/ke...')\n#9 \/var\/www\/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Template\/TemplateFileLocator.php","Line":56}`

**Comment by alincota** [comment] 2016-11-18 22:34
I get exactly the same thing. Any requirements for this app that we are not aware of? as in version of nextcloud?

I personally installed the app by doing git clone and then copying keeweb folder under my 3rd party apps folder.

**Comment by jhass** [comment] 2016-11-24 18:37
Duplicate of #16

**Closed by jhass** 2016-11-24 18:37 UTC
