### ISSUE TITLE
Support KeePass files stored in Nextcloud

### ISSUE THREAD

**Issue by maxolasersquad** [jhass/nextcloud-keeweb#142] opened 2020-04-17 18:29 UTC
Unless I'm missing it, it seems that KeePass files stored locally, on a WebDav share, Dropbox, Google Drive, and OneDrive. Oddly missing is the ability to select a file stored within Nextcloud.

**Comment by Sammus187** [comment] 2020-04-20 10:20
I only use it for key databases stored on nextcloud: navigate to the database file on nextcloud and click on it. I didn't realise this app could open keepass files stored anywhere *except* those in Nextcloud.

**Comment by jhass** [comment] 2020-04-20 10:24
I would say this is a duplicate of #43

**Closed by jhass** 2020-04-20 10:24 UTC

**Comment by maxolasersquad** [comment] 2020-04-24 01:42
Okay, so if I double-click the KeePass file from the Files app then it opens in the KeeWeb app for decrypting. However, if I start from the KeeWeb application my options are "Open", which browses my file system, or "More" which provides options gives me the options to either generate a new file, choose a WebDav share, or go to Settings. It seems that there should be a way from this screen to choose a NextCloud file.
