### ISSUE TITLE
after save can't open kdbx in keeweb

### ISSUE THREAD

**Issue by Momosquiton** [jhass/nextcloud-keeweb#57] opened 2017-07-19 17:34 UTC
i have a .kdbx in shared folder on NC12
I have open the file, edit and saved.
After the save if click on file the system open the download and not the keeweb app
Sorry for my english

**Comment by jhass** [comment] 2017-07-19 19:36
Duplicate of #34

**Closed by jhass** 2017-07-19 19:36 UTC
