### ISSUE TITLE
Internal server error => template file not found: template:keeweb

### ISSUE THREAD

**Issue by caco3** [jhass/nextcloud-keeweb#17] opened 2016-09-10 15:30 UTC
I tried to use it on Nextcloud 10.0, but get an Internal server error when I start the app or the password db file.

Nextcloud shows this log entry:
```
Exception: {
    "Exception":"Exception",
    "Message":"template file not found: template:keeweb",
    "Code":0,
    "Trace":"#0 \/home\/myowncloud\/www\/nextcloud\/lib\/private\/legacy\/template.php(197): OC\\Template\\TemplateFileLocator->find('keeweb')\n#1 \/home\/myowncloud\/www\/nextcloud\/lib\/private\/legacy\/template.php(84): OC_Template->findTemplate('',
    'keeweb',
    'keeweb')\n#2 \/home\/myowncloud\/www\/nextcloud\/lib\/public\/AppFramework\/Http\/TemplateResponse.php(151): OC_Template->__construct('keeweb',
    'keeweb',
    '')\n#3 \/home\/myowncloud\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(113): OCP\\AppFramework\\Http\\TemplateResponse->render()\n#4 \/home\/myowncloud\/www\/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Keeweb\\Controller\\PageController),
    'keeweb')\n#5 \/home\/myowncloud\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('PageController',
    'keeweb',
    Object(OC\\AppFramework\\DependencyInjection\\DIContainer),
    Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/home\/myowncloud\/www\/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler),
    Array)\n#8 \/home\/myowncloud\/www\/nextcloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/keeweb\/ke...')\n#9 \/home\/myowncloud\/www\/nextcloud\/index.php(48): OC::handleRequest()\n#10 {main}",
    "File":"\/home\/myowncloud\/www\/nextcloud\/lib\/private\/Template\/TemplateFileLocator.php",
    "Line":56
} 
```

**Comment by caco3** [comment] 2016-09-10 15:44
It might me related to https://github.com/jhass/nextcloud-keeweb/issues/16

**Comment by jhass** [comment] 2016-09-10 15:45
How exactly did you install?

**Comment by caco3** [comment] 2016-09-10 15:47
I downloaded the master as a zip file and copied the folder keeweb to my nextcloud apps folder.

**Comment by jhass** [comment] 2016-09-10 15:53
Yes, that's not supported and makes this a duplicate of #16. Please either use a release tarball or follow the dev setup instructions in the readme.

**Closed by jhass** 2016-09-10 15:53 UTC

**Comment by caco3** [comment] 2016-09-10 15:56
Thanks!
With the release it works (was blind before, didn't see the releases :( )
