### ISSUE TITLE
Nextcloud 13

### ISSUE THREAD

**Issue by nougad** [jhass/nextcloud-keeweb#67] opened 2017-12-25 18:20 UTC
Nextcloud 13 beta 3 is already out since a week: https://nextcloud.com/blog/nextcloud-13-beta-3-ready-for-your-testing-go-and-win-a-t-shirt/

Unfortunately keeweb is not supported yet. It results in the error:

> App "Keeweb" cannot be installed because it is not compatible with this version of the server. 

Any plans to support NC13?

**Comment by mr-bolle** [comment] 2017-12-28 08:26
Hi nougad, 

you can adjust the dependencies / max-version, and activate the App again.

[*keeweb/appinfo/info.xml*](https://raw.githubusercontent.com/jhass/nextcloud-keeweb/master/keeweb/appinfo/info.xml)
>     <dependencies>
>         <nextcloud min-version="11" max-version="13" />
>     </dependencies>

**Comment by jhass** [comment] 2018-01-04 16:40
Tbh. I'm reluctant to update this to support NC 13 until #34 is resolved. I consider the current state essentially broken and doing an update would give a false sense of progress on that. Last time I checked, #34 couldn't be resolved without new upstream features (I consider having to statically register each and every mimetype upstream improper), but I couldn't check, track or push for the necessary upstream changes due to lack of time and motivation. I would be happy if anybody could do that.

Meanwhile I'm open to workarounds that don't heavily degrade performance.

**Comment by e-alfred** [comment] 2018-01-29 11:38
@jhass Which upstream features would be needed for this app to be useable again?

**Comment by jhass** [comment] 2018-01-29 12:07
A reliable and performant way to update the mime type registry from a plugin.

**Comment by e-alfred** [comment] 2018-01-29 23:32
@jhass Maybe this issue covers your problem as well:

https://github.com/nextcloud/server/issues/8105

**Comment by Yetangitu** [comment] 2018-01-29 23:41
https://github.com/nextcloud/server/issues/8105 is a feature request (map apps to mime types) unrelated to #34 (mapping extensions to mime types).

**Comment by jhass** [comment] 2018-01-30 09:20
While 8105 would surely greatly simplify this plugin, what @Yetangitu said is true. The prequisite to easily asosciate an app with a mimetype is, for keeweb, to register new ones.

**Comment by sbrl** [comment] 2018-02-07 16:33
The [manual workaround suggested](https://github.com/jhass/nextcloud-keeweb/issues/34#issuecomment-313841308) in #34 worked for me. Perhaps a guide on editing the file (or even doing it automagically) would help?

**Comment by jhass** [comment] 2018-02-07 16:38
I don't want that anywhere near an official method to do it, sorry. It's prone to errors and will be overwritten by updates.

**Comment by sbrl** [comment] 2018-02-07 16:42
Ah, good point. Never mind then. We're waiting on support from Nextcloud then, I suppose. There is an issue opened against Nextcloud for this, right?

**Comment by jhass** [comment] 2018-02-08 08:28
I don't know, I currently don't have the time to follow Nextcloud development, sorry.

**Comment by franklupo** [comment] 2018-03-15 15:21
Any news?

**Comment by justintime4tea** [comment] 2018-04-01 18:48
If you use https://YOUR_DOMAIN/apps/keeweb?open=/file.kdbx it will open the app and place it in recent (recent gets cleared periodically).

This will require version bump in app info.

You can use External Sites app to embed a direct link to your KDBX with an icon in the Navbar of the Nextcloud interface.

This is far from ideal but it works well enough for myself! Would love if I could find some time to take a look at this integration project and contribute to Nextcloud 13 support.

**Comment by danger89** [comment] 2018-04-26 15:10
Owwh I'm so existed to switch from LastPass to Keeweb... :grin: Once this is all fixed, I will go to keeweb anytime soon...

**Comment by oakbrad** [comment] 2018-04-26 20:08
I can activate the app after making the required version change, but I just get an "Internal Server Error" but there are no details and I'm not seeing anything wrong in my logs. Likewise if I try using the URL @justintime4tea suggested with the path to my file.

I thought maybe permissions error but chmod 777 didn't correct it.

I also was not sure whether to place this app in custom_apps or apps subfolder, but I get the same behavior in both (seems like it should go in custom_apps).

Anyone using this successfully on a current NC13 installation? I am using the stable docker image.

**Comment by justintime4tea** [comment] 2018-04-27 23:42
@oakbrad, I'm also using NC13 docker container. I know that doesn't help much, but for reference in case anyone is wondering. I'll take a look sometime this weekend and see if I did anything special and can share my docker volume mount configuration and any other info that can help.

**Comment by oakbrad** [comment] 2018-04-28 02:08
Actually I got it working by deleting and starting over. I think I possibly had a permissions issue with Docker.

The other thing I did differently was set "max-version" at 14. I wonder if this is necessary since I'm on 13.0.1.

**Comment by arnowelzel** [comment] 2018-07-06 11:20
@jhass  There are other apps out there which have the same problem, for example Ownpad.

But they deal with it by explaining how to add the custom mimetype:

https://apps.nextcloud.com/apps/ownpad

This links to the documentation as following:

https://github.com/otetard/ownpad/blob/master/README.md#mimetype-detection

Even though this is not ideal, it's better than naving no app at all.

I did this for Keeweb and it works totally fine in my NC 13 instance.

**Comment by mr-bolle** [comment] 2018-07-06 12:20
@arnowelzel: Great :+1:, could you please update the Readme.md for this app with you adjustments. And send a pull request, if i find some time i would test your solution.

**Comment by DJCrashdummy** [comment] 2018-07-06 15:32
yes, also *Audio Player* [suggests this "workaround"](https://github.com/rello/audioplayer/wiki/audio-files-and-mime-types#add-custom-mime-types).

**Comment by arnowelzel** [comment] 2018-07-07 23:45
@mr-bolle I just created the pull request for the Readme.md updated.

**Comment by e-alfred** [comment] 2018-08-16 00:30
Now Nextcloud 14 is around the corner, Is this app still compatible with it? NC 14 brings a lot of breaking changes, so it would be interesting to see if it still works.

**Comment by zerpex** [comment] 2018-09-06 10:08
And now, NC14 is here.

The trick to modify info.xml does not work anymore (well, it does, but the result is not usable) and we ,the users, need a usable version.

I know the talk is still in progress (since NC13 release...), but maybe you can release a temporary fix to make keeweb usable again until you found a definitive solution ?
Or fork to an unstable branch ?

And why not upgrade keeweb to 1.6 at the same time ? ;)

Don't get myself wrong, I really appreciate your work and thank you a lot for that !

Regards,
z.

**Comment by sbrl** [comment] 2018-09-11 18:12
Hey, @onny! Have you considered opening a [Pull Request](https://help.github.com/articles/about-pull-requests/) for that?

**Comment by zerpex** [comment] 2018-09-12 17:14
@onny Confirmed.

Thanks for the tip, but it would be nice if the project goes on again :)

**Comment by Li-An** [comment] 2018-09-27 09:50
Sorry to interfer but trying to install the extension as explained and it’s not possible to activate it. I suppose I have to wait for a new version ?

**Comment by arnowelzel** [comment] 2018-09-27 10:17
@Li-An you have to set "max-version" in `apps/keeweb/appinfo/info.xml` to 14 or higher:

```
<dependencies>
    <nextcloud min-version="11" max-version="14" />
</dependencies>
```

And of course you also need to modify `apps/keeweb/css/style.css`:

```
#app {
  overflow-y: hidden;
  width: 100%;
}

#app > iframe {
  width: 100%;
  height: 100%;
}
```

Is there already a pull request for that?

**Comment by danger89** [comment] 2018-09-27 10:46
max version to 13 yes there are PRs, but not yet 14 ><...
There is no PR with this CSS  change. Futhermore should you consider taking this minetype detection be part your your PR as well? https://github.com/jhass/nextcloud-keeweb/pull/81/files

**Comment by Li-An** [comment] 2018-09-27 10:47
@arnowelzel thanks a lot. I will have have look.

**Comment by e-alfred** [comment] 2018-09-29 14:57
I think not releasing the app to the App Store is not the best idea. If it is listed as an app there, available for the latest release, then more users can be reached (and Keepass pretty much a de facto standard now even getting a software audit by the EU) which could generate enough support to get the missing feature implemented upstream (maybe either by someone implementing it or providing enough money through Bountysource so somebody tackles it for example).

**Comment by Gymnae** [comment] 2018-11-05 17:44
Agree, keeweb is dropping off the radar. Rather an intermediate solution now to keep the user base and grow it than to wait until an alternative takes over.

**Comment by dugite-code** [comment] 2018-12-11 01:36
It's been quite a while now we are approaching the end of the year. isn't it time to probably accept mimetype registration isn't coming any time soon and just accept admins will have to be responsible?

At the very least merging a pull requests making it all compatible with nc14 to allow manual installation without updating the store page.

**Comment by sbrl** [comment] 2018-12-12 18:57
It might be worth creating a temporary fork in order to merge a bunch of PRs, and then potentially co-ordinate a re-merge at a later time if this project is no longer maintained.

**Comment by e-alfred** [comment] 2018-12-23 12:15
@jhass Regarding the Mimetype problem: Maybe you could take a look at the Epub reader app that can do mimetype registrations for certain filetypes: https://github.com/Yetangitu/owncloud-apps/blob/457c1603fad5132ed17e27e99642c56381f169a0/files_reader/lib/Controller/PageController.php

**Comment by jhass** [comment] 2019-01-18 10:36
@e-alfred Sorry, could you be more specific? I fail to understand how that makes it work unfortunately. Pull requests that adapt the method to this plugin are more than welcome!

**Comment by Thatoo** [comment] 2019-02-05 11:19
Would that plugin not help to solve the problem?
https://github.com/vavrecan/keeweb-local-server

**Comment by jhass** [comment] 2019-02-05 12:02
No, not at all.

**Comment by jhass** [comment] 2019-02-11 19:39
Try 0.5.0

Never tested it for NC13 but it should work :)

Take care to do the required manual steps as outlined in the readme!

**Closed by jhass** 2019-02-11 19:39 UTC
Labels: enhancement, help wanted

**Comment by arnowelzel** [comment] 2019-02-11 19:49
@jhass Great news! Thanks for all your work!
