### ISSUE TITLE
Nextcloud 20 Error

### ISSUE THREAD

**Issue by OMNiTRiX98** [jhass/nextcloud-keeweb#165] opened 2020-10-09 12:11 UTC
Since i've updated my nextcloud there is a issue with keeweb. It is not listed as an active app and when i try to activate it, i get an error „App "keeweb" cannot be installed because appinfo file cannot be read.“. When i remove the app and try to install it i get the same message. After a logoff the app is still displayed als installed but not active and the cycle repeats. Any idea how to fix this?

**Comment by jhass** [comment] 2020-10-09 12:15
Duplicate of #163 I guess

**Comment by arnowelzel** [comment] 2020-11-29 23:29
I fixed a compliance error reported by `occ app:check-code keeweb`with 6e19e01ef8566590e9d4783d46b0e319f99f7938 - maybe this also caused this error. However, I couldn't reproduce this effect in my NC 20 test setup.

**Comment by arnowelzel** [comment] 2020-12-14 01:00
@OMNiTRiX98 can you please check the latest version (0.6.4) of Keeweb if this problem is still present?

**Comment by arnowelzel** [comment] 2021-11-30 19:50
Since nothing changed for nearly one year I will close this now.

**Closed by arnowelzel** 2021-11-30 19:50 UTC
